#pragma once

#include <cstdint>
#include <memory>
#include <string>
#include <vector>

struct smt_audio_context {
    smt_audio_context(const smt_audio_context &)             = delete;
    smt_audio_context & operator=(const smt_audio_context &) = delete;
    ~smt_audio_context();

    // Initialize from SMT config directory. The directory may contain either:
    // 1. config.json with an "audio_model" section, or
    // 2. a split-encoder metadata json generated by the export script.
    static std::unique_ptr<smt_audio_context> create(const std::string & config_dir, bool warmup = true);

    // Encode an audio file using the configured SMT audio ONNX pipeline.
    // Returns audio embedding vector (n_tokens * hidden_size floats).
    std::vector<float> encode_audio(const std::string & audio_path);

    // Get the hidden size (decoder-side embedding dimension)
    int64_t hidden_size() const;

    // Get the model architecture name
    const std::string & architecture() const;

  private:
    smt_audio_context() = default;
    struct impl;
    std::unique_ptr<impl> pimpl_;
};
